# Generated by Django 4.1 on 2023-02-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ImageField(default=56, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
