# Generated by Django 2.2.28 on 2023-02-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.CharField(default='About', max_length=255),
        ),
        migrations.AddField(
            model_name='contact',
            name='title',
            field=models.CharField(default='Contact', max_length=255),
        ),
    ]
