# Generated by Django 4.1 on 2023-02-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_contact_email_alter_contact_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
