# Generated by Django 4.1 on 2023-02-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_address_contact_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(default='Contact-Info', max_length=255),
        ),
    ]
