# Generated by Django 4.1 on 2023-02-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_contact_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='body',
        ),
        migrations.AddField(
            model_name='contact',
            name='footer',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
