# Generated by Django 4.1 on 2023-02-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_contact_body_contact_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='footer',
            field=models.TextField(max_length=500),
        ),
    ]
