# Generated by Django 4.1 on 2023-02-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_contact_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='footer',
            field=models.TextField(max_length=200),
        ),
    ]
