# Generated by Django 4.1 on 2023-02-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_contact_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Fusion and PLasmas', max_length=255)),
                ('footer', models.TextField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='footer',
        ),
    ]
